### ISSUE TITLE
SDK executables signed for MacOS

### ISSUE THREAD

**Issue by piot** [coherence/skeleton-unity#5]
Executables and bundles are signed and cause no issues on MacOS.

[Story #1](https://docs.google.com/spreadsheets/d/1cSc8So_xDwIKZNQ8wdySZi5ylm6ssWK8LieUJB90tZw/edit#gid=0&range=D2)

**Comment by eriksvedang** [comment]
This should be fixed now, though I'm not completely ready to trust that it works until I've heard more reports from various members of the team. I'll leave it open in the meantime.
