### ISSUE TITLE
Synchronized spinning cube

### ISSUE THREAD

**Issue by piot** [coherence/skeleton-unity#6]
The build connects to the local replication server and shows a simple 2D cube synchronizing across the network.

[Story #1](https://docs.google.com/spreadsheets/d/1cSc8So_xDwIKZNQ8wdySZi5ylm6ssWK8LieUJB90tZw/edit#gid=0&range=D2)

**Comment by eriksvedang** [comment]
This is solved in `master` of https://github.com/coherence/skeleton-unity
